name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          TEMP=$(mktemp)
          echo "${{ secrets.DEPLOY_KEY }}" > $TEMP
          ssh -o StrictHostKeyChecking=no -i $TEMP -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOST }} /mnt/data/caddy/static/doses/.update
      - name: Check
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 30
          max_attempts: 5
          retry_wait_seconds: 2
          warning_on_retry: false
          command: curl -sSL --fail -m 10 https://static.augendre.info/doses/ > /dev/null
